In [5]:
import array

arr = array.array('i', [1, 2, 3, 4, 5])
lst = list(arr)
print(lst)


[1, 2, 3, 4, 5]


In [6]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
diag_sum = np.trace(arr)
print(diag_sum)


15


In [7]:
a = [[1, 2], [3, 5]]
x = 2
result = [val for sublist in a for val in sublist if val > x]
print(result)


[3, 5]


In [8]:
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
C = A + B
print(C)


[[10 10 10]
 [10 10 10]
 [10 10 10]]
